before_install:
  - sudo apt-get install -y aspell hunspell
  - sudo apt-get install -y myspell-en-us myspell-en-za myspell-en-gb
language: node_js
env:
  - CXX=g++-4.8
node_js:
  - '6.2'
  - '5.1'
  - '4.2'
  - '0.12'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8



